auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 江行的晨暮
<<<<<<< HEAD
url: http://sunurdy.github.io/
feed: /atom.xml
author_info: <a href="http://sunurdy.github.io/">江行的晨暮</a>
=======
url: 
feed: /atom.xml
author_info: 
>>>>>>> origin/master
